import email.policy instead of email.
Running `python test.py` works fine, but when you actually install the pacakge, you get an error:

```
>>> import emailcompat32crlf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maurits/community/emailcompat32crlf/emailcompat32crlf/__init__.py", line 6, in <module>
    email.policy.Compat32.linesep = "\r\n"
    ^^^^^^^^^^^^
AttributeError: module 'email' has no attribute 'policy'
```